### ISSUE TITLE
On the issue of the integrity of the program

### ISSUE THREAD

**Issue by s673456** [TuanTTranCS/wRRLoadBalancer#1]
Dear Author, First of all, thank you for sharing your results on github. Regarding the file simu5g/slicing that you referenced in the wRRLoadBalancer project, I understand that the VNF folder you made public is only a sub-file of it, and there are other files such as gtp, liveConfigurations, and so on, which have already been declared in your project that don't appear in your project, and a query to the simu5g-related project, I can't find any related content. Therefore, I would like to ask you to provide the complete project information including the declared but not uploaded files.

**Comment by TuanTTranCS** [comment]
Hi @s673456, thank you for your interest in the project. The 5G slices network environment was built by my colleagues based on the existing Simu5G framework (https://github.com/Unipisa/Simu5G). 

You can refer to my teammates' work on the 5G slice-level traffic generator: https://spectrum.library.concordia.ca/id/eprint/990258/1/Ding_MCompSc_S2022.pdf

The codes and my work in this project are to improve an existing feature of the VNF packet load balancer from my teammate. It is a small part of my thesis, which you can find at: https://spectrum.library.concordia.ca/id/eprint/992047   

Due to IP concerns with the company I did research with, I cannot make the whole simulation environment public. If you have any further interest to discuss, please email me. Thank you.
